name: Docker

on:
    workflow_dispatch:
      inputs:
        release_version:
          description: "Release version"
          required: true
          type: string
          default: ""
        base_hash:
          description: "Commit hash from which to build"
          required: true
          type: string
          default: ""
        publish:
          description: "Publish to Docker Hub"
          required: true
          type: boolean
          default: false
    workflow_call:
      inputs:
        release_version:
          description: "Release version"
          required: true
          type: string
        base_hash:
          description: "Commit hash from which to build"
          required: true
          type: string
        publish:
          description: "Publish to Docker Hub"
          required: true
          type: boolean
      secrets:
        DOCKERHUB_USERNAME:
          required: false
        DOCKERHUB_TOKEN:
          required: false
        S3_ACCESS_KEY_ID:
          required: false
        S3_ACCESS_KEY:
          required: false

permissions:
  contents: read

concurrency:
  group: docker-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IROH_FORCE_STAGING_RELAYS: "1"

jobs:
    build_and_publish:
      permissions:
        contents: read
      if: >-
        github.repository == 'manaflow-ai/iroh' &&
        github.event_name != 'merge_group' &&
        ((github.event_name != 'pull_request' && github.event_name != 'pull_request_target') || (github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]'))
      timeout-minutes: 30
      name: Docker
      runs-on: [self-hosted, linux, X64]
      steps:
        - name: Checkout
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
          with:
            persist-credentials: false

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e

        - name: Login to Docker Hub
          uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Prep dirs
          run: |
            mkdir -p bins/linux/amd64
            mkdir -p bins/linux/arm64

        - name: Download awscli
          run: |
            mkdir -p ~/awscli
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o ~/awscli/awscliv2.zip
            cd ~/awscli && unzip -oq awscliv2.zip

        - name: Install awscli
          run: sudo ~/awscli/aws/install --update
    
        - name: Fetch release binaries
          env:
            BASE_HASH: ${{ inputs.base_hash }}
            AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-west-2
          run: |
            aws s3 cp "s3://vorc/iroh-relay-linux-amd64-musl-${BASE_HASH}" bins/linux/amd64/iroh-relay
            aws s3 cp "s3://vorc/iroh-dns-server-linux-amd64-musl-${BASE_HASH}" bins/linux/amd64/iroh-dns-server

            aws s3 cp "s3://vorc/iroh-relay-linux-aarch64-musl-${BASE_HASH}" bins/linux/arm64/iroh-relay
            aws s3 cp "s3://vorc/iroh-dns-server-linux-aarch64-musl-${BASE_HASH}" bins/linux/arm64/iroh-dns-server

        - name: Build Docker image (iroh-relay)
          uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
          with:
            context: .
            push: ${{ inputs.publish }}
            tags: n0computer/iroh-relay:latest,n0computer/iroh-relay:${{ inputs.release_version }}
            target: iroh-relay
            platforms: linux/amd64,linux/arm64/v8
            file: docker/Dockerfile.ci

        - name: Build Docker image (iroh-dns-server)
          uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
          with:
            context: .
            push: ${{ inputs.publish }}
            tags: n0computer/iroh-dns-server:latest,n0computer/iroh-dns-server:${{ inputs.release_version }}
            target: iroh-dns-server
            platforms: linux/amd64,linux/arm64/v8
            file: docker/Dockerfile.ci
